[SDPA-5279] Cheerio update
dpc-sdp/ripple pull request #1119
Opened 2022-01-11 03:52 UTC by waitingallday

## Motivation and Context

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5279

## Changed

1. Upgraded `cheerio` to `1.0.0-rc.10` in `@dpc-sdp/ripple-markup`
2. Changed unit test to load HTML via loader, added multi nbsp test
3. Updated snapshot

## How Has This Been Tested?

* Added another content case (multi nbsp) to markup transpiler test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist

- [ ] I've added relevant changes to the documentation.
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] My change requires a template update for create-ripple-app.
- [ ] I have added template update script for next release.

2022-01-11 03:56 UTC, ChrisCampbellCodes approved these changes

2022-01-12 05:03 UTC, dylankelly approved these changes

2022-01-12 05:04 UTC, dylankelly requested changes

2022-01-12 05:04 UTC, dylankelly commented on packages/ripple-nuxt-tide/lib/config/markup-plugins.js
> +        node.data = node.data.replace(String.fromCodePoint(codepoint), entity)
Add this back in @waitingallday

2022-01-13 04:28 UTC, dylankelly approved these changes

2022-01-14 00:09 UTC, merged