[SDPA-5945] IFrame embed media title.
dpc-sdp/ripple pull request #1194
Opened 2022-05-12 03:01 UTC by edyuenyw

## Motivation and Context

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5945

## Changed

1. Embedded video title is missing from embedded media video plugin. Added title element for the iframe for this plugin. 

### Screenshots
After change the title tag will appear in the iframe.
<img width="524" alt="image" src="https://user-images.githubusercontent.com/67810118/167983447-b290b130-177e-4cf0-b49b-977e70549834.png">

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist

- [ ] I've added relevant changes to the documentation.
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] My change requires a template update for create-ripple-app.
- [ ] I have added template update script for next release.

2022-05-12 04:36 UTC, waitingallday requested changes
Change `element.attr('title')` to `iframe.attr('title')`

2022-05-12 04:36 UTC, waitingallday commented on packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap
> +<rpl-embedded-video width=\\"854\\" height=\\"480\\" src=\\"https://www.youtube.com/embed/Xb4ElZqit8k?autoplay=0&amp;start=0&amp;rel=0\\" title class=\\"rpl-markup__embedded-video\\" variant=\\"link\
It's still not quite right - this top half is run with plugins, while the second half is without. So the test run _with_ plugins isn't rendering the title. I can see in the plugins code you're using `element.attr('title')` but the fixture has title on the iframe itself, ie. `iframe.attr('title')`.

2022-05-12 06:56 UTC, waitingallday approved these changes

2022-05-16 23:04 UTC, ChrisCampbellCodes approved these changes

2022-06-02 00:53 UTC, merged